version: 2.1

default_config: &default_config
  docker:
    - image: "circleci/openjdk:11.0.2"
  working_directory: ~/project

commands:
  gradle:
    parameters:
      cmd:
        type: string
        default: "build"
    steps:
      - run: ./gradlew << parameters.cmd >>
  save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  restore_workspace:
    steps:
      - attach_workspace:
          at: ~/project
  restore_gradle:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
  save_gradle:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  compile:
    <<: *default_config
    steps:
      - checkout
      - restore_gradle
      - gradle:
          cmd: compileKotlin compileTestKotlin
      - save_gradle
      - save_workspace
  test:
    <<: *default_config
    steps:
      - restore_workspace
      - restore_gradle
      - gradle:
          cmd: test jacocoTestReport
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml
  build:
    <<: *default_config
    steps:
      - restore_workspace
      - restore_gradle
      - gradle:
          cmd: build -x test
      - save_workspace
  publish:
    <<: *default_config
    steps:
      - restore_workspace
      - restore_gradle
      - gradle:
          cmd: bintrayUpload -x build -x test

workflows:
  version: 2.1
  ctp:
    jobs:
      - compile
      - test:
          requires:
            - compile
      - build:
          requires:
            - compile
      - hold:
          type: approval
          requires:
            - build
            - test
      - publish:
          requires:
            - hold
