version: 2.1

commands:
  restore_gradle_wrapper:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_gradle_dependencies:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
  save_gradle_wrapper:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
  save_gradle_dependencies:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle.kts" }}
          paths:
            - ~/.gradle/caches
  gradle:
    parameters:
      cmd:
        type: string
        default: "build"
    steps:
      - run: ./gradlew << parameters.cmd >>

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: "circleci/openjdk:11.0.2"
    steps:
      - checkout
      - restore_gradle_wrapper
      - restore_gradle_dependencies
      - gradle:
          cmd: build
      - save_gradle_wrapper
      - save_gradle_dependencies
      - gradle:
          cmd: test jacocoTestReport
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml
